name: Test Logging

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-logging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add dependencies if required (e.g., pytest or specific libraries)
          pip install -r requirements.txt || true  # Optional: Only if you have requirements.txt

      - name: Run logging tests
        run: |
          python test_logging.py
